===============================
Mu Intermediate Representation
===============================

The client generates code in the format of **Mu Intermediate Representation**,
or **Mu IR** for short. The IR is the language in which programs are represented
in the Mu micro VM. The Mu IR is defined by the `Mu specification
<https://github.com/microvm/microvm-spec/wiki/uvm-ir>`__.

The client submits one **bundle** (a piece of Mu IR code) at a time to the Mu
micro VM. A bundle defines many *types*, *constants*, *global cell* and
*functions*. After submitting, Mu knows about those things and may compile the
functions now or later, depending on implementation. The client can define more
such things by submitting more bundles one after another.

If you have used LLVM before, the Mu IR is the counterpart of LLVM modules.



.. vim: tw=80
